CREATE TABLE IF NOT EXISTS empresas (
  id_empresa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  cnpj VARCHAR(20),
  status VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS planos (
  id_plano BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  preco_mensal NUMERIC(10,2) NOT NULL,
  limite_usuarios INT NOT NULL,
  limite_os_mes INT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS assinaturas (
  id_assinatura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  id_plano BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL, -- ATIVA, INADIMPLENTE, CANCELADA
  data_inicio DATE,
  proximo_ciclo DATE,
  gateway_ref VARCHAR(120),
  CONSTRAINT fk_assinatura_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT fk_assinatura_plano FOREIGN KEY (id_plano) REFERENCES planos(id_plano),
  CONSTRAINT uk_empresa_assinatura UNIQUE (id_empresa)
);

CREATE TABLE IF NOT EXISTS pagamentos (
  id_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_assinatura BIGINT NOT NULL,
  valor NUMERIC(10,2) NOT NULL,
  data_pagamento TIMESTAMP,
  status VARCHAR(20) NOT NULL, -- PAGO, FALHOU, ESTORNADO
  referencia VARCHAR(120),
  CONSTRAINT fk_pagamento_assinatura FOREIGN KEY (id_assinatura) REFERENCES assinaturas(id_assinatura)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  senha_hash VARCHAR(128) NOT NULL,
  role VARCHAR(20) NOT NULL, -- SUPERADMIN, ADMIN, OPERADOR
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_usuario_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT uk_usuario_email UNIQUE (email)
);
-- Domínio da oficina
CREATE TABLE IF NOT EXISTS clientes (
  id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  nome VARCHAR(100) NOT NULL,
  telefone VARCHAR(20),
  email VARCHAR(100),
  endereco VARCHAR(255),
  CONSTRAINT fk_clientes_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa)
);

CREATE TABLE IF NOT EXISTS veiculos (
  id_veiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  id_cliente BIGINT,
  placa VARCHAR(10) NOT NULL,
  marca VARCHAR(50),
  modelo VARCHAR(50),
  ano INT,
  chassi VARCHAR(50),
  CONSTRAINT fk_veiculos_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT fk_veiculos_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
  CONSTRAINT uk_veiculos_empresa_placa UNIQUE (id_empresa, placa)
);

CREATE TABLE IF NOT EXISTS ordens_servico (
  id_os BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  id_cliente BIGINT,
  id_veiculo BIGINT,
  data_abertura TIMESTAMP,
  data_finalizacao TIMESTAMP,
  status VARCHAR(20),
  observacoes VARCHAR(2000),
  CONSTRAINT fk_os_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT fk_os_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
  CONSTRAINT fk_os_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculos(id_veiculo)
);

CREATE TABLE IF NOT EXISTS servicos_os (
  id_servico_os BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  id_os BIGINT,
  descricao VARCHAR(2000) NOT NULL,
  valor NUMERIC(10,2) NOT NULL,
  CONSTRAINT fk_servicos_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT fk_servicos_os_os FOREIGN KEY (id_os) REFERENCES ordens_servico(id_os)
);

CREATE TABLE IF NOT EXISTS pecas_os (
  id_peca_os BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa BIGINT, -- NULL para SUPERADMIN

  id_os BIGINT,
  descricao VARCHAR(2000) NOT NULL,
  quantidade INT NOT NULL,
  valor_unitario NUMERIC(10,2) NOT NULL,
  CONSTRAINT fk_pecas_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
  CONSTRAINT fk_pecas_os_os FOREIGN KEY (id_os) REFERENCES ordens_servico(id_os)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_clientes_empresa ON clientes(id_empresa);
CREATE INDEX IF NOT EXISTS idx_veiculos_empresa ON veiculos(id_empresa);
CREATE INDEX IF NOT EXISTS idx_os_empresa ON ordens_servico(id_empresa);
CREATE INDEX IF NOT EXISTS idx_servicos_empresa ON servicos_os(id_empresa);
CREATE INDEX IF NOT EXISTS idx_pecas_empresa ON pecas_os(id_empresa);
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON usuarios(id_empresa);
CREATE INDEX IF NOT EXISTS idx_assinatura_empresa ON assinaturas(id_empresa);
